name: Tests

on: [push, pull_request]

jobs:
  Unit_Tests_Tools:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install the Google test suite
      env:
        MAKEFLAGS: "-j 2"
      run: (cd test; make install-googletest)
    - name: Build and run the tools unit tests
      env:
        MAKEFLAGS: "-j 2"
      run: (cd tools; make all; make run_tests)

  Gen_Test_Matrix:
    outputs:
      matrix: ${{ steps.files.outputs.matrix }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate Matrix of unit tests
      id: files
      run: |
        JSONI=$(find test -name *_test.cpp -type f | sed 's,test/,,;s,_test.cpp$,,' | xargs -I {} echo -e '"{}",')
        # Remove last "," and add closing brackets
        if [[ $JSONI == *, ]]; then
        JSONI="${JSONI%?}"
        fi
        JSONI=${JSONI//$'\n'}
        echo $JSONI
        # Set output
        echo "::set-output name=matrix::[${JSONI}]"

  Unit_Test:
    needs: Gen_Test_Matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: ${{fromJson(needs.Gen_Test_Matrix.outputs.matrix)}}

    steps:
    - uses: actions/checkout@v2
    - name: Install the Google test suite
      env:
        MAKEFLAGS: "-j 2"
      run: (cd test; make install-googletest)
    - name: Build and run unit test ${{ matrix.test }}
      env:
        MAKEFLAGS: "-j 2"
      run: (cd test; make run-${{ matrix.test }})
